/run/initialize

/vis/open OGL 600x600-0+0

/vis/viewer/set/viewpointVector 1 1 1    
/vis/viewer/set/autoRefresh true

/vis/drawVolume 

/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate  
/vis/scene/add/scale 10 cm 
/vis/scene/add/axes -10 -10 -10 5 cm
/vis/scene/add/eventID



/vis/trajectory/set/particle alpha blue
/vis/trajectory/set/particle Li7 green
/vis/trajectory/set/particle e- red
/vis/trajectory/set/particle gamma yellow